feat: extended bootstrap to fit the theme
kavindu25/frontend-training-avantrio pull request #1
Opened 2022-07-20 11:31 UTC by kavindu25

2022-07-20 12:28 UTC, diniththarushka reviewed
Go through the comments and make the required changes.

We'll use a page (Temporarily) to have the customized components as shown in the UI guide. So you can get a clear view of all the customizations while you are doing it.

2022-07-20 12:28 UTC, diniththarushka commented on webapp/src/components/forms/SubmitButton.jsx
> +      btnClass += " btn-secondary";
If the `variant` is `outlined`, the button should have a border and should not be filled. Keep in mind that you can always add more variants according to the requirement!

2022-07-20 12:28 UTC, diniththarushka commented on webapp/src/custom.scss
> +$h1-font-size: 64px;
let's maintain all values using `rem` s (Except border-radius and box-shadow). That will help us to maintain more responsive layout in relation to the ***root element sizes***

1 rem = 16px

2022-07-20 12:28 UTC, diniththarushka commented on webapp/src/custom.scss
> +    font-family: 'Gilroy';
We can customize buttons by only extending bootstrap. Having external styles are not required. Refer [**Sass variables**](https://getbootstrap.com/docs/5.2/components/buttons/#variables) section in documentation or `_variables.scss` in bootstrap library to find out what you can customize!

2022-07-22 09:22 UTC, kavindu25 commented on webapp/src/custom.scss
> +$h1-font-size: 64px;
Changed necessary px values to rem

2022-07-22 09:24 UTC, kavindu25 commented on webapp/src/custom.scss
> +    font-family: 'Gilroy';
Kept the external styles for now

2022-07-22 09:26 UTC, kavindu25 commented on webapp/src/components/forms/SubmitButton.jsx
> +      btnClass += " btn-secondary";
Changed the btn class name to btn-outline since the given secondary btn type is a outline variant

2022-07-27 04:51 UTC, diniththarushka requested changes
1. In `CreateIcon.jsx` usages some are not working as expected. In some buttons, border radius is not enough. Refer to the design.
2. Shall we make the heading bold (to look good ;) )
3. Make the below requested change(s) as well

2022-07-27 04:51 UTC, diniththarushka commented on webapp/src/components/CreateIcon.jsx
> +    if (iconVariant === "type1") {
This variant type is considered as an `enum`. You can have this under `constants.js` and access from there. This will improve the consistency

2022-07-28 05:41 UTC, diniththarushka approved these changes

2022-07-28 05:41 UTC, merged